### ISSUE TITLE
Node stuck: there are more imported non-finalized blocks in the database that can fit into the forest

### ISSUE THREAD

**Issue by stakesafebart** [Cardinal-Cryptography/aleph-node-issues#11]
### Did you read the documentation and guides?

- [X] I have inspected the documentation.

### Is there an existing issue?

- [X] I have searched the existing issues.

### Description of the problem

When a node is out of sync and restarts, the process panicks and exits. This is a major problem. When nodes get desynced and undergo a reboot, they could end up in a state where they can't operate or progress further.

Log file:

Successful start:
2023-10-27 12:20:37 Aleph Node
2023-10-27 12:20:37 ✌️  version 0.12.0-1a00a8fd94e
2023-10-27 12:20:37 ❤️  by Cardinal:Aleph Zero Foundation, 2021-2023
2023-10-27 12:20:37 📋 Chain specification: Aleph Zero Testnet
2023-10-27 12:20:37 🏷  Node name: StakeSafe Amsterdam Backup1
2023-10-27 12:20:37 👤 Role: AUTHORITY
2023-10-27 12:20:37 💾 Database: RocksDb at /home/adminbart/aleph-node/data/chains/testnet/db/full
2023-10-27 12:20:39 🔨 Initializing Genesis block/state (state: 0x0324…640d, header-hash: 0x05d5…60c5)
No backup path provided, using default path: "/home/adminbart/aleph-node/data/backup-stash" for AlephBFT backups. Please do not remove this folder
2023-10-27 12:20:40 Using default protocol ID "sup" because none is configured in the chain specs
2023-10-27 12:20:40 🏷  Local node identity is: 12D3KooWMVDLapz4BLSfy2cAS7Z4QEi3k4Jo6y4FSwskLGyQffUw
2023-10-27 12:20:40 🔍 Discovered new external address for our node: /ip4/x.x.x.x/tcp/30333/p2p/12D3KooWMVDLapz4BLSfy2cAS7Z4QEi3k4Jo6y4FSwskLGyQffUw
2023-10-27 12:20:40 💻 Operating system: linux
2023-10-27 12:20:40 💻 CPU architecture: x86_64
2023-10-27 12:20:40 💻 Target environment: gnu
2023-10-27 12:20:40 💻 CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
2023-10-27 12:20:40 💻 CPU cores: 2
2023-10-27 12:20:40 💻 Memory: 15384MB
2023-10-27 12:20:40 💻 Kernel: 4.18.0-448.el8.x86_64
2023-10-27 12:20:40 💻 Linux distribution: CentOS Stream 8
2023-10-27 12:20:40 💻 Virtual machine: yes
2023-10-27 12:20:40 📦 Highest known block at #0
2023-10-27 12:20:40 〽 Prometheus exporter started at 127.0.0.1:9615
2023-10-27 12:20:40 Running JSON-RPC server: addr=0.0.0.0:xxxx, allowed origins=["*"]
2023-10-27 12:20:40 Running session 0.
2023-10-27 12:20:40 Clique Network status: not maintaining any connections;
2023-10-27 12:20:40 Network status report: authentication connected peers - 0; block sync connected peers - 0;
2023-10-27 12:20:41 Failed to handle sync request response from PeerId("12D3KooWRkGLz4YbVmrsWK75VjFTs8NvaBu42xhAmQaP4KeJpw1L"): cannot import a block that we do not consider required.
2023-10-27 12:20:42 Failed to handle sync request response from PeerId("12D3KooWRkGLz4YbVmrsWK75VjFTs8NvaBu42xhAmQaP4KeJpw1L"): cannot import a block that we do not consider required.
2023-10-27 12:20:42 Failed to handle sync request response from PeerId("12D3KooWEXRFPyi8vSwF68VV8Q1XDSbW4trR2krt7hCxBYADjkaG"): cannot import a block that we do not consider required.
2023-10-27 12:20:42 Failed to handle sync request response from PeerId("12D3KooWGkheQPyNYTCQPqGgJN82UXVmfnzqTcUsNYkjeTGe9hA5"): cannot import a block that we do not consider required.
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x2806…1119
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0xb921…9c8c
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0xba9e…f2e0
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x950d…a32a
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0xb466…0df6
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0xa0a2…14db
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x08db…0acb
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0xc208…9220
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x8438…4d6b
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x33d7…15d0
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x1625…76fd
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x8f1b…4416
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x2ca0…ec1d
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x7102…a85a
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0xd651…5022
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x31bf…2e77
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x7f02…a116
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x88a9…ac6a
2023-10-27 12:20:42 Pinned block cache limit reached. Evicting value. hash = 0x55af…38c9

After a forced reboot:
2023-10-27 12:21:34 Aleph Node
2023-10-27 12:21:34 ✌️  version 0.12.0-1a00a8fd94e
2023-10-27 12:21:34 ❤️  by Cardinal:Aleph Zero Foundation, 2021-2023
2023-10-27 12:21:34 📋 Chain specification: Aleph Zero Testnet
2023-10-27 12:21:34 🏷  Node name: StakeSafe Amsterdam Backup1
2023-10-27 12:21:34 👤 Role: AUTHORITY
2023-10-27 12:21:34 💾 Database: RocksDb at /home/adminbart/aleph-node/data/chains/testnet/db/full
No backup path provided, using default path: "/home/adminbart/aleph-node/data/backup-stash" for AlephBFT backups. Please do not remove this folder
2023-10-27 12:21:37 Using default protocol ID "sup" because none is configured in the chain specs
2023-10-27 12:21:37 🏷  Local node identity is: 12D3KooWMVDLapz4BLSfy2cAS7Z4QEi3k4Jo6y4FSwskLGyQffUw
2023-10-27 12:21:37 🔍 Discovered new external address for our node: /ip4/x.x.x.x/tcp/30333/p2p/12D3KooWMVDLapz4BLSfy2cAS7Z4QEi3k4Jo6y4FSwskLGyQffUw
2023-10-27 12:21:37 💻 Operating system: linux
2023-10-27 12:21:37 💻 CPU architecture: x86_64
2023-10-27 12:21:37 💻 Target environment: gnu
2023-10-27 12:21:37 💻 CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
2023-10-27 12:21:37 💻 CPU cores: 2
2023-10-27 12:21:37 💻 Memory: 15384MB
2023-10-27 12:21:37 💻 Kernel: 4.18.0-448.el8.x86_64
2023-10-27 12:21:37 💻 Linux distribution: CentOS Stream 8
2023-10-27 12:21:37 💻 Virtual machine: yes
2023-10-27 12:21:37 📦 Highest known block at #11476
2023-10-27 12:21:37 〽 Prometheus exporter started at 127.0.0.1:9615
2023-10-27 12:21:37 Running JSON-RPC server: addr=0.0.0.0:xxxx, allowed origins=["*"]
2023-10-27 12:21:37 Clique Network status: not maintaining any connections;

====================

Version: 0.12.0-1a00a8fd94e

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
      std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   4: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   5: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   6: finality_aleph::nodes::run_validator_node::{{closure}}
   7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   8: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
   9: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  10: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  11: tokio::runtime::park::CachedParkThread::block_on
  12: tokio::runtime::context::runtime::enter_runtime
  13: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  14: tokio::runtime::task::core::Core<T,S>::poll
  15: tokio::runtime::task::harness::Harness<T,S>::poll
  16: tokio::runtime::blocking::pool::Inner::run
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  20: start_thread
  21: clone

Thread 'tokio-runtime-worker' panicked at 'Failed to initialize Sync service: forest initialization error: there are more imported non-finalized blocks in the database that can fit into the forest – purge the block database and restart $

This is a bug. Please report it at:

        docs.alephzero.org

### Information on your setup.

Compiled code / Version: 0.12.0-1a00a8fd94e
CentOS 8 Stream
Run directly

### Steps to reproduce

Run on testnet with 0.12.0-1a00a8fd94e
Make sure the ledger is out of date
Restart aleph-node one or two times

### Did you attach relevant logs?

- [X] I have attached logs (if relevant).

**Comment by kostekIV** [comment]
Thank you, we managed to reproduce and are currently working on a fix. We will keep you updated.

**Comment by kostekIV** [comment]
Recently published release 12.1 fixes this issue.  If it still does not work please let us know, otherwise we will close the issue in one week
